Merged revisions 32433-32441,32445-32448,32452-32453,32455,32457,32459-32461 via svnmerge from https://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk
........
  r32433 | res2002 | 2009-06-04 13:00:23 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Get rid of specific shaders, renderloop remnants, lightmaps
........
  r32434 | res2002 | 2009-06-04 14:18:16 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Prevent an SV binary compatibility issue between debug and optimize builds.
........
  r32435 | res2002 | 2009-06-04 14:24:09 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Don't hit config manager every frame to query max portal recurse count
........
  r32436 | res2002 | 2009-06-04 14:32:40 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Also emit string markers in optimize builds (they're useful & cheap enough)
........
  r32437 | res2002 | 2009-06-04 16:28:08 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  Some DrawSimpleMesh enhancements:
  - Ability to specify index ranges like in rendermesh
  - Method for bulk-drawing multiple simplemeshes
........
  r32438 | res2002 | 2009-06-04 16:28:36 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Improve CEGUI drawing
........
  r32439 | res2002 | 2009-06-04 17:00:37 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Implement DrawSimpleMeshes()
........
  r32440 | res2002 | 2009-06-04 21:59:36 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Reduced csShaderVariable memory footprint
........
  r32441 | res2002 | 2009-06-04 22:42:20 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Add iView::GetCustomMatrixCamera()
........
  r32445 | sunshine | 2009-06-04 23:10:07 +0200 (Thu, 04 Jun 2009) | 2 lines
  
  Fixed compilation error: operands of ?: have different types
........
  r32446 | sunshine | 2009-06-04 23:20:06 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  'weltall' improved csCommandLineParser::GetName() documentation.
  From #663.
........
  r32447 | sunshine | 2009-06-04 23:22:36 +0200 (Thu, 04 Jun 2009) | 3 lines
  
  'weltall' added multi-file processing capability to 'docconv'.
  Closes #663.
........
  r32448 | res2002 | 2009-06-04 23:30:46 +0200 (Thu, 04 Jun 2009) | 1 line
  
  Copy comment improvement from r32446 to public interface.
........
  r32452 | res2002 | 2009-06-05 01:30:05 +0200 (Fri, 05 Jun 2009) | 1 line
  
  Update for new cs-win32libs
........
  r32453 | crystal-manage | 2009-06-05 05:17:55 +0200 (Fri, 05 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32455 | res2002 | 2009-06-05 13:53:32 +0200 (Fri, 05 Jun 2009) | 1 line
  
  Remove wxtypical MSVC workspace - WX is now shipped with cs-win32libs, so the app+plugin using it can be in the 'typical' workspace as well
........
  r32457 | crystal-manage | 2009-06-05 14:45:29 +0200 (Fri, 05 Jun 2009) | 7 lines
  
  master header files: Automated master header file repair.
  Visual-C++ project files: Automated Visual-C++ project file repair.
  Texinfo files: Automated Texinfo @node and @menu repair.
  Swig Python files: Automated Swig Python file repair.
  Swig Perl5 files: Automated Swig Perl5 file repair.
  User's Manual: Automated Texinfo to HTML conversion.
........
  r32459 | res2002 | 2009-06-07 20:23:02 +0200 (Sun, 07 Jun 2009) | 1 line
  
  Don't link external libraries from _all_ plugins into static plugin library users
........
  r32460 | res2002 | 2009-06-07 20:27:55 +0200 (Sun, 07 Jun 2009) | 1 line
  
  Clean up plugins excluded from MSVC static plugins lib
........
  r32461 | res2002 | 2009-06-07 20:58:47 +0200 (Sun, 07 Jun 2009) | 1 line
  
  Correctly deal with platforms in per-file configurations
........